### ISSUE TITLE
Handling duplicate slug values

### ISSUE THREAD

**Issue by Taik** [jagi/meteor-astronomy-slug-behavior#1]
Hi!

I'm really liking astronomy, and am converting the majority of my codebase over to it. 
Question regarding this module: For slugs, there can often be the case where the there might be duplicate values whereas the slug should be globally unique. More often than not I simply just append a numerical value to the slug (ex: not-unique-2, not-unique-3)  to make the slug unique.

What do you think about adding support for this?

**Comment by lukejagodzinski** [comment]
Hi, yes the uniqueness of a slug was in plans from the beginning. I just wanted the main astronomy code base to get more stable.

The only problem with a slug is tha it will only be reliable when executed on the server because you may encounter (on the client) a situation when you are not subscribed to the entire set of documents. Even executing it both on the client and server (using Meteor method) may cause strange behavior. Let's say that you want to redirect (routing) to newly created doc. You will need to wait for the server response so you have correct slug.

But the same problem you have right now. I will probably implement this feature in this or next week. Stay tuned.

**Comment by Taik** [comment]
Thanks your your hard work, I'll be looking forward to it.

**Comment by lukejagodzinski** [comment]
I'm implementing this feature right now and I have one problem with it. It will be very inefficient way of generating slugs because it uses a regular expression (in Mongo) to find all the slugs with the pattern `^slug-\d+$`. I will implement it that way but I was also thinking about a different solution. Instead adding number, we could add hash something like: `slug-sd342d`. Of course it's not so pretty. But maybe it will be an option for people caring about performance.

**Comment by Taik** [comment]
Thanks for the update! Both solutions seems viable to me.

Regarding the first solution (which is what I do right now), it isn't that inefficient assuming the index is correctly set up for the slug field. That brings me to a side question, is ensuring indexes something we can do with Astronomy? (I'm referring to something like SimpleSchema's ensureIndex)

**Comment by lukejagodzinski** [comment]
Ok I've published new version with unique slugs.

Yes indexes is the feature that I missed and I will add it in the next update of Astronomy. Right now you can however add indexes right to the collection:

``` js
Collection._ensureIndex(keys, options);
```
