### ISSUE TITLE
Please add translit for cyrillic letters

### ISSUE THREAD

**Issue by SPAHI4** [jagi/meteor-astronomy-slug-behavior#2]

**Comment by lukejagodzinski** [comment]
It doesn't work right now? The list of characters and their replacements are not made by me. I would have to investigate it. Do you know some good website where I can find the replacements for Cyrillic?

**Comment by SPAHI4** [comment]
Yes, cyrillic lettes replaced by a void now.
Sure

```
var roman = ["Sch","sch",'Yo','Zh','Kh','Ts','Ch','Sh','Yu','ya','yo','zh','kh','ts','ch','sh','yu','ya','A','B','V','G','D','E','Z','I','Y','K','L','M','N','O','P','R','S','T','U','F','','Y','','E','a','b','v','g','d','e','z','i','y','k','l','m','n','o','p','r','s','t','u','f','','y','','e'];
var cyrillic = ["Щ","щ",'Ё','Ж','Х','Ц','Ч','Ш','Ю','я','ё','ж','х','ц','ч','ш','ю','я','А','Б','В','Г','Д','Е','З','И','Й','К','Л','М','Н','О','П','Р','С','Т','У','Ф','Ь','Ы','Ъ','Э','а','б','в','г','д','е','з','и','й','к','л','м','н','о','п','р','с','т','у','ф','ь','ы','ъ','э'];
```

**Comment by lukejagodzinski** [comment]
I would like to be 100% sure that it's correct. So help me with a few thing.

First of all I only need small letters because I'm using native JavaScript `toLowerCase()` function to make it lower case and later I perform transliteration.

I've found here https://en.wikipedia.org/wiki/Cyrillic_alphabets the Cyrillic alphabet and letters names. I assume that names don't translate to transliteration but in some cases they do.

I also need unicode numbers for each letter which can be found here https://en.wikipedia.org/wiki/Cyrillic_script_in_Unicode

I've also noticed that you have some extra characters. What are they? And some characters don't have transliteration. Why?

Could you write here only small letters in the following form?

CYRILLIC_CHARACTER | ROMAN_TRANSLIT | UNICODE_NUMBER

Example:

ф | f | 0444

**Comment by SPAHI4** [comment]
Caracters "ь" and "ъ" - "soft sign" and "hard sign", usually does not represent a sound, but modifies the sound of the preceding letter, indicating palatalization.
Some characters doesn't have any analog from english alphabet and they replaces with 2 or sometimes 3 characters, for example, Щ => Sch.
You can find more here https://en.wikipedia.org/wiki/Romanization_of_Russian

**Comment by lukejagodzinski** [comment]
Ok thanks.
I've noticed that the щ letter in your example has `sch` transliteration but the website from the link you posted says it should be `shch`. Who is right? :) And I see that they are changing transliteration from time to time.

**Comment by SPAHI4** [comment]
I think wikipedia is right)

**Comment by lukejagodzinski** [comment]
Ok, so I will add it with the next astronomy release. Stay tuned

**Comment by lukejagodzinski** [comment]
Transliteration for Cyrillic added in the 1.0.0-rc.2 version of the slug behavior
